PLAINTIFFS = []  # истец
DEFENDANTS = []  # ответичк
THIRDS = []  # Третьи лица
OTHERS = []  # Дрегие лица
INN = []  # ИНН
DATE = []  # дата дела
NUMBERS_CASE = []  # номер дела
ESSENCE_OF_CASE = []  # суть дела
COURTS = []  # суд
